theme: jekyll-theme-minimal
title: Digests of Bandit Algorithms
description: This site includes *my* summaries from the <a href="https://tor-lattimore.com/downloads/book/book.pdf">Bandit Algorithm</a>
