theme: jekyll-theme-minimal
title: Digests of Bandit Algorithms
description: This site includes *my* summaries from the <a href="www.test.com">aaaa</a> [Bandit Algorithm](https://tor-lattimore.com/downloads/book/book.pdf) book. 
